import goods_2 from "@/assets/images/goods/goods_2.png";
import goods_3 from "@/assets/images/goods/goods_3.png";
import goods_4 from "@/assets/images/goods/goods_4.png";
import goods_5 from "@/assets/images/goods/goods_5.png";
import goods_6 from "@/assets/images/goods/goods_6.png";
import goods_7 from "@/assets/images/goods/goods_7.png";
import goods_8 from "@/assets/images/goods/goods_8.png";
import goods_9 from "@/assets/images/goods/goods_9.png";
import goods_10 from "@/assets/images/goods/goods_10.png";
import goods_11 from "@/assets/images/goods/goods_11.png";
import goods_12 from "@/assets/images/goods/goods_12.png";
import goods_13 from "@/assets/images/goods/goods_13.png";
import goods_14 from "@/assets/images/goods/goods_14.png";
import goods_15 from "@/assets/images/goods/goods_15.png";
import goods_16 from "@/assets/images/goods/goods_16.png";
import goods_17 from "@/assets/images/goods/goods_17.png";
import goods_18 from "@/assets/images/goods/goods_18.png";
import goods_19 from "@/assets/images/goods/goods_19.png";
import goods_20 from "@/assets/images/goods/goods_20.png";
import goods_21 from "@/assets/images/goods/goods_21.png";
import goods_22 from "@/assets/images/goods/goods_22.png";
import goods_23 from "@/assets/images/goods/goods_23.png";
import goods_24 from "@/assets/images/goods/goods_24.png";

import goods_icon_5 from "@/assets/images/goods/goods_icon_5.png";
import goods_icon_8 from "@/assets/images/goods/goods_icon_8.png";
import goods_icon_9 from "@/assets/images/goods/goods_icon_9.png";
import goods_icon_10 from "@/assets/images/goods/goods_icon_10.png";
import goods_icon_11 from "@/assets/images/goods/goods_icon_11.png";
import goods_icon_12 from "@/assets/images/goods/goods_icon_12.png";
import goods_icon_13 from "@/assets/images/goods/goods_icon_13.png";
import goods_icon_16 from "@/assets/images/goods/goods_icon_16.png";
import goods_icon_17 from "@/assets/images/goods/goods_icon_17.png";
import goods_icon_18 from "@/assets/images/goods/goods_icon_18.png";

import goods_sign_13 from "@/assets/images/goods/goods_sign_13.png";
import goods_sign_17 from "@/assets/images/goods/goods_sign_17.png";

// 模拟数据
// goodList 中列表数据
export const GOOD_LIST = [
  {
    img: '',
    no: 'GIFT',
    title: 'GIFT MEMBERSHIP',
    type: 0,
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    price1: '225',
    price2: '56',
    id: 1,
  },
  {
    img: '',
    no: 'GIFT',
    title: 'GIFT CARD',
    type: 1,
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    price1: '125',
    price2: '21',
    id: 2,
  },
  {
    img: goods_2,
    no: 'CASK NO. 4.294',
    title: 'AN AURA OF RESPECTABILITY',
    type: 2,
    flavour: 'Lightly Peated',
    age: '18 years',
    region: 'Highland, Island',
    cask: 'First Fill Pedro Ximenez barrique STR',
    price1: '325',
    price2: '41',
    color: '#BDD78D',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_3,
    no: 'CASK NO. 4.303',
    title: 'A nocturne sipper',
    type: 2,
    flavour: 'Oily & Coastal',
    age: '16 years',
    region: 'Highland, Island',
    cask: 'First Fill Pedro Ximenez barrique STR',
    price1: '250',
    price2: '56',
    color: '#276B9A',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_4,
    no: 'CASK NO. 6.69',
    title: 'Tyrant, show thy face!',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '10 years',
    region: 'Highland Southern',
    cask: 'Second-fill Sherry butt',
    price1: '125',
    price2: '58',
    color: '#71307C',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_5,
    no: 'CASK NO. 9.291',
    title: 'Roll on a happy hay bale',
    type: 2,
    flavour: 'Oily & Coastal',
    age: '20 years',
    region: 'Speyside Spey',
    cask: 'First-fill barrel',
    price1: '290',
    price2: '36',
    color: '#AC599E',
    isNew: true,
    isRightIcon: goods_icon_5,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 6,
  },
  {
    img: goods_6,
    no: 'CASK NO. 12.80',
    title: 'Heaven in a leather hammock',
    type: 2,
    flavour: 'Spicy & Dry',
    age: '34 years',
    region: 'Speyside, Lossie',
    cask: 'First-fill Spanish oak Pedro Ximenez butt',
    price1: '1195',
    price2: '13',
    color: '#F8AE53',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 7,
  },
  {
    img: goods_7,
    no: 'CASK NO. 6.69',
    title: 'The rose garden',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '19 years',
    region: 'Highland Eastern',
    cask: 'First-fill barrel',
    price1: '240',
    price2: '40',
    color: '#71307C',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 8,
  },
  {
    img: goods_8,
    no: 'CASK NO. 35.331',
    title: 'Ultra hoggie',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '27 years',
    region: 'Speyside, Lossie',
    cask: 'First-fill toasted oak hogshead',
    price1: '445',
    price2: '27',
    color: '#BC3434',
    isRightIcon: goods_icon_8,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 9,
  },
  {
    img: goods_9,
    no: 'CASK NO. 53.430',
    title: "Doesn't hold back",
    type: 2,
    flavour: 'Peated',
    age: '10 years',
    region: 'Islay',
    cask: 'Refill hogshead',
    price1: '150',
    price2: '78',
    color: '#74AF3E',
    isNew: true,
    isRightIcon: goods_icon_9,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 10,
  },
  {
    img: goods_10,
    no: 'CASK NO. 146.2',
    title: "Join the great tumult",
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '6 years',
    region: 'England',
    cask: 'First-fill barrique, shaved/toasted/re-charred',
    price1: '145',
    price2: '44',
    color: '#71307C',
    isRightIcon: goods_icon_10,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 11,
  },
  {
    img: goods_11,
    no: 'CASK NO. G8.27',
    title: "Looks good in leather",
    type: 2,
    flavour: 'Spicy & Dry',
    age: '32 years',
    region: 'Lowland',
    cask: 'First-fill barrel',
    price1: '295',
    price2: '31',
    color: '#F8AE53',
    isNew: true,
    isRightIcon: goods_icon_11,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 12,
  },
  {
    img: goods_12,
    no: 'CASK NO. 41.176',
    title: "Baristaliscious",
    type: 2,
    flavour: 'Juicy Oak & Vanilla',
    age: '17 years',
    region: 'Speyside Spey',
    cask: 'First-fill Chinkapin oak barrel, HTMC',
    price1: '185',
    price2: '4',
    color: '#60A8D3',
    isRightIcon: goods_icon_12,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 13,
  },
  {
    img: goods_13,
    no: 'CASK NO. 44.145',
    title: "Pilgrimage to El Rocio",
    type: 2,
    flavour: 'Deep Rich & Dried Fruits',
    age: '13 years',
    region: 'Speyside Spey',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '155',
    price2: '14',
    color: '#E6782A',
    isRightIcon: goods_icon_13,
    isSignIcon: goods_sign_13,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 14,
  },
  {
    img: goods_14,
    no: 'BUNDLE',
    title: "March into Spring!",
    type: 3,
    flavour: "Deep Rich & Dried Fruits,Juicy Oak & Vanilla,Spicy & Sweet",
    age: '8 years, 10 years, 16 years',
    region: 'Speyside, Highland, Speyside',
    cask: 'First-fill barrel, Second-fill Sherry butt, First-fill Chinkapin oak barrel HTMC',
    desc: 'Our March into Spring! bundle is sure to stoke some cask-strength conversation with a trio of tantalizing malts, each representing a unique flavour profile in indyllic fashion. Kick off the season right with this first-class flight!',
    price1: '375',
    price2: '16',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 15,
  },
  {
    img: goods_15,
    no: 'BUNDLE',
    title: "Embrace the Extraordinary",
    type: 3,
    desc: 'Embrace the extraordinary when discovering these unique Society casks from the Speyside and Highlands! This selection provides a rare opportunity to learn about the nuances between varied oak protocols.',
    price1: '645',
    price2: '14',
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 16,
  },
  {
    img: goods_16,
    no: 'BUNDLE',
    title: "International Women’s Day Duo",
    type: 3,
    desc: 'Celebrate International Women’s Day with two extraordinary casks chosen by an all-female tasting panel! In celebration of last year’s International Women’s Day, this tasting panel of exceptional palates carefully selected a handful of different casks for this year’s celebration. Today, a remarkable duo of 20-year-old malts is ready for your collection!',
    price1: '560',
    price2: '36',
    color: '#2E2E2D',
    isNew: true,
    isRightIcon: goods_icon_16,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 17,
  },
  {
    img: goods_17,
    no: 'CASK NO. B7.13',
    title: "C’est si bon!",
    type: 2,
    flavour: 'Bourbon',
    age: '4 years',
    region: 'Indiana, USA',
    cask: 'First-fill American oak #4 charred barrel, #2 charred heads',
    price1: '65',
    price2: '32',
    color: '#202448',
    isRightIcon: goods_icon_17,
    isSignIcon: goods_sign_17,
    hovered: false,
    hovered1: false,
    page: 'goodlist',
    productNum: 1,
    id: 18,
  }
];
// join 中商品列表
export const JOIN_GOODS_LIST = [
  {
    img: goods_12,
    no: 'Cask No. 35.359',
    title: 'the classic',
    type: 2,
    flavour: 'Juicy 0ak & Vanilla',
    age: '9 years',
    region: 'Speyside, Lossie',
    cask: 'First-fill barrel',
    abv: '58.9',
    produced: '217',
    price1: '170',
    color: '#60A8D3',
    tip: 'If ordered separately, Membership is 99, Cask No. 35.359 is 120',
    id: 1,
  },
  {
    img: goods_2,
    no: 'Cask No. 35.359',
    title: 'Even-handed smoke',
    type: 2,
    flavour: 'Lightly Peated',
    age: '12 years',
    region: 'Highland, Eastern',
    cask: 'Refill barrel',
    abv: '60.0',
    produced: '180',
    price1: '195',
    color: '#74AF3E',
    tip: 'If ordered separately, Membership is 99, Cask No. 66.203 is 145',
    id: 2,
  },
  {
    img: goods_4,
    no: 'Cask No. 9.261',
    title: 'What a delight',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '19 years',
    region: 'Speyside, Spey',
    cask: 'First-fill barrel',
    abv: '54.5',
    produced: '204',
    price1: '260',
    color: '#71307C',
    tip: 'If ordered separately, Membership is 99, Cask No. 9.261 is 210',
    id: 3,
  }
];

// collect 商品列表
export const COLLECT_GOODS_LIST = [
  {
    img: goods_18,
    no: 'BUNDLE',
    title: 'Spring Whisky Adventures',
    type: 3,
    desc: "Our Spring Whisky Adventures bundle features four casks with a stunning spectrum of aromas and flavours to indulge in. If you're looking for 'the full package' to explore different cask protocols, regions, and whisky styles to kick off your Spring collection, this is it!",
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '545',
    price2: '30',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_2,
    no: 'CASK NO. 4.365',
    title: 'You only live once',
    type: 2,
    flavour: 'Lightly Peated',
    age: '11 years',
    region: 'Highland, Island',
    cask: 'First-fill barrel',
    price1: '125',
    price2: '30',
    color: '#BDD78D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 2,
  },
  {
    img: goods_5,
    no: 'CASK NO. 9.248',
    title: 'A major treat',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '18 years',
    region: 'Speyside, Spey',
    cask: 'First-fill barrel',
    price1: '220',
    price2: '40',
    color: '#AC599E',
    isNew: true,
    isRightIcon: goods_icon_18,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_9,
    no: 'CASK NO. 10.258',
    title: 'QUO UADIS',
    type: 2,
    flavour: 'Peated',
    age: '9 years',
    region: 'Islay',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '155',
    price2: '8',
    color: '#74AF3E',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_4,
    no: 'CASK NO. 39.277',
    title: 'A darker side',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '11 years',
    region: 'Speyside, Lossie',
    cask: 'First-fill barrel',
    price1: '130',
    price2: '57',
    color: '#71307C',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_11,
    no: 'CASK NO. 55.87',
    title: 'The stage is set',
    type: 2,
    flavour: 'Spicy & Dry',
    age: '16 years',
    region: 'Highland Northern',
    cask: 'First-fill ex-bodega Oloroso butt',
    price1: '205',
    price2: '70',
    color: '#F8AE53',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 6,
  },
  {
    img: goods_19,
    no: 'CASK NO. 78.74',
    title: 'Cheeky wee upstart',
    type: 2,
    flavour: 'Young & Spritely',
    age: '9 years',
    region: 'Highland Western',
    cask: 'Second-fill Pedro Ximenez hogshead',
    price1: '130',
    price2: '94',
    color: '#d298c4',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 7,
  },
  {
    img: goods_13,
    no: 'CASK NO. 95.79',
    title: "Cross-cultural",
    type: 2,
    flavour: 'Deep Rich & Dried Fruits',
    age: '14 years',
    region: 'Speyside Lossie',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '160',
    price2: '19',
    color: '#E6782A',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 8,
  },
  {
    img: goods_12,
    no: 'CASK NO. 112.116',
    title: "Orchards in a blossom",
    type: 2,
    flavour: 'Juicy Oak & Vanilla',
    age: '8 years',
    region: 'Highland Southern',
    cask: 'First-fill barrel',
    price1: '110',
    price2: '49',
    color: '#60A8D3',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'collect',
    productNum: 1,
    id: 9,
  },
];

// bundle 商品列表
export const BUNDLE_GOODS_LIST = [
  {
    img: goods_18,
    no: 'BUNDLE',
    title: 'Spring Whisky Adventures',
    type: 3,
    desc: "Our Spring Whisky Adventures bundle features four casks with a stunning spectrum of aromas and flavours to indulge in. If you're looking for 'the full package' to explore different cask protocols, regions, and whisky styles to kick off your Spring collection, this is it!",
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '545',
    price2: '30',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_20,
    no: 'BUNDLE',
    title: 'You only live once',
    type: 3,
    desc: 'At The Scotch Malt Whisky Society, we love deeply complex and flavourful whisky in our glass. One way to achieve this is through secondary maturation in a wine cask. Here we have two different wine casks on feature – French dessert wine and Spanish sherry – to create a super-bloom of flavours!',
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '295',
    price2: '40',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_21,
    no: 'BUNDLE',
    title: 'Distillery Dive A5: Armagnac Amour',
    type: 3,
    desc: 'Experience liquid luxury in our newly-released Armagnac bundle, a must for any Society member eager to learn about the hidden treasures of Armagnac! 5.5 was crafted from the Colombard grape which brings more fruit aromas forward versus A5.6 from Ugni Blanc which brings more floral notes to the fore. On the palate, both expressions explode with classic Armagnac flavours that will impress any sherried whisky lover!',
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '725',
    price2: '21',
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_22,
    no: 'BUNDLE',
    title: 'Liquid Americana',
    type: 3,
    desc: 'Liquid Americana is here! We have curated selections from the middle of the country for a tremendous trio of designations – American single malt, bourbon and rye. These casks will impress palates with bold and beautiful expressions from Texas and Indiana!',
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '260',
    price2: '34',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_23,
    no: 'BUNDLE',
    title: 'Magical Islay',
    type: 3,
    desc: 'Most scotch whisky lovers already know what a magical island Islay is. Discover two of the most sought-after distilleries from this wondrous place like never before! Two distinct styles from world-famous distilleries await in this unparalleled glimpse of Islay magic in a bottle!',
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '995',
    price2: '419',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_21,
    no: 'BUNDLE',
    title: 'Ron & Rum',
    type: 3,
    desc: 'In the spirit of exploration, we happily present the Ron & Rum bundle for seasoned rum aficionados and curious connoisseurs to indulge in. Spanish styled ‘Ron’ rums are typically column-distilled, offering lighter color and flavour, whilst British styled rums are traditionally pot-distilled, yielding darker color and richer flavour. Juxtapose the two for a Caribbean-inspired flavour escape!',
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '275',
    price2: '9',
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 6,
  },
  {
    img: goods_24,
    no: 'BUNDLE',
    title: 'Spring Gala Tasting',
    type: 3,
    desc: 'It’s a “Black Label Affair” at the Spring Gala! Superbly aged malts from the Highlands and Speyside strut their stuff on the red carpet for an unforgettable night of single malt excellence. Behold what beautiful nuances and complexities may be garnered from careful maturation in an ex-bourbon cask. Three very different styles of whisky are on display for your complete enjoyment!',
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '725',
    price2: '29',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'bundle',
    productNum: 1,
    id: 7,
  },
];

// whisky 商品列表
export const WHISKY_GOODS_LIST = [
  {
    img: goods_18,
    no: 'BUNDLE',
    title: 'Spring Whisky Adventures',
    type: 3,
    desc: "Our Spring Whisky Adventures bundle features four casks with a stunning spectrum of aromas and flavours to indulge in. If you're looking for 'the full package' to explore different cask protocols, regions, and whisky styles to kick off your Spring collection, this is it!",
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '545',
    price2: '30',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_2,
    no: 'CASK NO. 4.365',
    title: 'You only live once',
    type: 2,
    flavour: 'Lightly Peated',
    age: '11 years',
    region: 'Highland, Island',
    cask: 'First-fill barrel',
    price1: '125',
    price2: '30',
    color: '#BDD78D',
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 2,
  },
  {
    img: goods_3,
    no: 'CASK NO. 4.303',
    title: 'A nocturne sipper',
    type: 2,
    flavour: 'Oily & Coastal',
    age: '16 years',
    region: 'Highland Island',
    cask: 'First-fill Oloroso barrique STR',
    price1: '250',
    price2: '48',
    color: '#276b9a',
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_2,
    no: 'CASK NO. 4.365',
    title: 'You only live once',
    type: 2,
    flavour: 'Lightly Peated',
    age: '11 years',
    region: 'Highland Island',
    cask: 'First-fill barrel',
    price1: '125',
    price2: '30',
    color: '#bdd78d',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_4,
    no: 'CASK NO. 9.248',
    title: 'A MAJOR TREAT',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '18 years',
    region: 'Speyside, Spey',
    cask: 'First-fill barrel',
    price1: '220',
    price2: '40',
    color: '#71307C',
    isNew: true,
    isRightIcon: goods_icon_18,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_5,
    no: 'CASK NO. 9.291',
    title: 'ROLL ON A HAPPY HAY BALE',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '20 years',
    region: 'Speyside Spey',
    cask: 'First-fill barrel',
    price1: '290',
    price2: '10',
    color: '#71307C',
    isNew: true,
    isRightIcon: goods_icon_5,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 6,
  },

  {
    img: goods_19,
    no: 'CASK NO. 78.74',
    title: 'Cheeky wee upstart',
    type: 2,
    flavour: 'Young & Spritely',
    age: '9 years',
    region: 'Highland Western',
    cask: 'Second-fill Pedro Ximenez hogshead',
    price1: '130',
    price2: '94',
    color: '#d298c4',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 7,
  },
  {
    img: goods_13,
    no: 'CASK NO. 95.79',
    title: "Cross-cultural",
    type: 2,
    flavour: 'Deep Rich & Dried Fruits',
    age: '14 years',
    region: 'Speyside Lossie',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '160',
    price2: '19',
    color: '#E6782A',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 8,
  },
  {
    img: goods_12,
    no: 'CASK NO. 112.116',
    title: "Orchards in a blossom",
    type: 2,
    flavour: 'Juicy Oak & Vanilla',
    age: '8 years',
    region: 'Highland Southern',
    cask: 'First-fill barrel',
    price1: '110',
    price2: '49',
    color: '#60A8D3',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 9,
  },
];

// vaults 商品列表
export const VAULTS_GOODS_LIST = [
  {
    img: goods_6,
    no: 'BUNDLE',
    title: 'Spring Whisky Adventures',
    type: 3,
    desc: "Our Spring Whisky Adventures bundle features four casks with a stunning spectrum of aromas and flavours to indulge in. If you're looking for 'the full package' to explore different cask protocols, regions, and whisky styles to kick off your Spring collection, this is it!",
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '545',
    price2: '30',
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_6,
    no: 'CASK NO. 4.365',
    title: 'You only live once',
    type: 2,
    flavour: 'Lightly Peated',
    age: '11 years',
    region: 'Highland, Island',
    cask: 'First-fill barrel',
    price1: '125',
    price2: '30',
    color: '#BDD78D',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 2,
  },
  {
    img: goods_6,
    no: 'CASK NO. 9.248',
    title: 'A major treat',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '18 years',
    region: 'Speyside, Spey',
    cask: 'First-fill barrel',
    price1: '220',
    price2: '40',
    color: '#AC599E',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_6,
    no: 'CASK NO. 10.258',
    title: 'QUO UADIS',
    type: 2,
    flavour: 'Peated',
    age: '9 years',
    region: 'Islay',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '155',
    price2: '8',
    color: '#74AF3E',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_6,
    no: 'CASK NO. 39.277',
    title: 'A darker side',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '11 years',
    region: 'Speyside, Lossie',
    cask: 'First-fill barrel',
    price1: '130',
    price2: '57',
    color: '#71307C',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_6,
    no: 'CASK NO. 55.87',
    title: 'The stage is set',
    type: 2,
    flavour: 'Spicy & Dry',
    age: '16 years',
    region: 'Highland Northern',
    cask: 'First-fill ex-bodega Oloroso butt',
    price1: '205',
    price2: '70',
    color: '#F8AE53',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 6,
  },
  {
    img: goods_6,
    no: 'CASK NO. 78.74',
    title: 'Cheeky wee upstart',
    type: 2,
    flavour: 'Young & Spritely',
    age: '9 years',
    region: 'Highland Western',
    cask: 'Second-fill Pedro Ximenez hogshead',
    price1: '130',
    price2: '94',
    color: '#d298c4',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 7,
  },
  {
    img: goods_6,
    no: 'CASK NO. 95.79',
    title: "Cross-cultural",
    type: 2,
    flavour: 'Deep Rich & Dried Fruits',
    age: '14 years',
    region: 'Speyside Lossie',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '160',
    price2: '19',
    color: '#E6782A',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 8,
  },
  {
    img: goods_6,
    no: 'CASK NO. 112.116',
    title: "Orchards in a blossom",
    type: 2,
    flavour: 'Juicy Oak & Vanilla',
    age: '8 years',
    region: 'Highland Southern',
    cask: 'First-fill barrel',
    price1: '110',
    price2: '49',
    color: '#60A8D3',
    hovered: false,
    hovered1: false,
    page: 'vaults',
    productNum: 1,
    id: 9,
  },
];

// single 商品列表
export const SINGLE_GOODS_LIST = [
  {
    img: goods_6,
    no: 'BUNDLE',
    title: 'Spring Whisky Adventures',
    type: 2,
    flavour: 'Rum',
    age: '18 years',
    region: 'Guyana',
    cask: 'Second-fill toasted French Oak barrique',
    price1: '180',
    price2: '46',
    color: '#202448',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_21,
    no: 'DISTILLERY DIVE A5: ARMAGNAC AMOUR',
    title: 'You only live once',
    desc: 'Experience liquid luxury in our newly-released Armagnac bundle, a must for any Society member eager to learn about the hidden treasures of Armagnac! 5.5 was crafted from the Colombard grape which brings more fruit aromas forward versus A5.6 from Ugni Blanc which brings more floral notes to the fore. On the palate, both expressions explode with classic Armagnac flavours that will impress any sherried whisky lover!',
    type: 3,
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '545',
    price2: '30',
    color: '#2E2E2D',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 2,
  },
  {
    img: goods_6,
    no: 'CASK NO. 9.248',
    title: 'A major treat',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '18 years',
    region: 'Speyside, Spey',
    cask: 'First-fill barrel',
    price1: '220',
    price2: '40',
    color: '#202448',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_6,
    no: 'CASK NO. 10.258',
    title: 'QUO UADIS',
    type: 2,
    flavour: 'Peated',
    age: '9 years',
    region: 'Islay',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '155',
    price2: '8',
    color: '#74AF3E',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_6,
    no: 'CASK NO. 39.277',
    title: 'A darker side',
    type: 2,
    flavour: 'Spicy & Sweet',
    age: '11 years',
    region: 'Speyside, Lossie',
    cask: 'First-fill barrel',
    price1: '130',
    price2: '57',
    color: '#71307C',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_6,
    no: 'CASK NO. 55.87',
    title: 'The stage is set',
    type: 2,
    flavour: 'Spicy & Dry',
    age: '16 years',
    region: 'Highland Northern',
    cask: 'First-fill ex-bodega Oloroso butt',
    price1: '205',
    price2: '70',
    color: '#F8AE53',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 6,
  },
  {
    img: goods_6,
    no: 'CASK NO. 78.74',
    title: 'Cheeky wee upstart',
    type: 2,
    flavour: 'Young & Spritely',
    age: '9 years',
    region: 'Highland Western',
    cask: 'Second-fill Pedro Ximenez hogshead',
    price1: '130',
    price2: '94',
    color: '#d298c4',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 7,
  },
  {
    img: goods_6,
    no: 'CASK NO. 95.79',
    title: "Cross-cultural",
    type: 2,
    flavour: 'Deep Rich & Dried Fruits',
    age: '14 years',
    region: 'Speyside Lossie',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '160',
    price2: '19',
    color: '#E6782A',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 8,
  },
  {
    img: goods_6,
    no: 'CASK NO. 112.116',
    title: "Orchards in a blossom",
    type: 2,
    flavour: 'Juicy Oak & Vanilla',
    age: '8 years',
    region: 'Highland Southern',
    cask: 'First-fill barrel',
    price1: '110',
    price2: '49',
    color: '#60A8D3',
    hovered: false,
    hovered1: false,
    page: 'single',
    productNum: 1,
    id: 9,
  },
];

// american 商品列表
export const AMERICAN_GOODS_LIST = [
  {
    img: goods_22,
    no: 'BUNDLE',
    title: 'LIQUID AMERICANA',
    type: 3,
    desc: "Liquid Americana is here! We have curated selections from the middle of the country for a tremendous trio of designations – American single malt, bourbon and rye. These casks will impress palates with bold and beautiful expressions from Texas and Indiana!",
    flavour: '',
    age: '',
    region: '',
    cask: '',
    price1: '545',
    price2: '30',
    color: '#2E2E2D',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 1,
  },
  {
    img: goods_2,
    no: 'CASK NO. 4.365',
    title: 'You only live once',
    type: 2,
    flavour: 'Lightly Peated',
    age: '11 years',
    region: 'Highland, Island',
    cask: 'First-fill barrel',
    price1: '125',
    price2: '30',
    color: '#BDD78D',
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 2,
  },
  {
    img: goods_3,
    no: 'CASK NO. 4.303',
    title: 'A nocturne sipper',
    type: 2,
    flavour: 'Oily & Coastal',
    age: '16 years',
    region: 'Highland Island',
    cask: 'First-fill Oloroso barrique STR',
    price1: '250',
    price2: '48',
    color: '#276b9a',
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 3,
  },
  {
    img: goods_2,
    no: 'CASK NO. 4.365',
    title: 'You only live once',
    type: 2,
    flavour: 'Lightly Peated',
    age: '11 years',
    region: 'Highland Island',
    cask: 'First-fill barrel',
    price1: '125',
    price2: '30',
    color: '#bdd78d',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 4,
  },
  {
    img: goods_4,
    no: 'CASK NO. 9.248',
    title: 'A MAJOR TREAT',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '18 years',
    region: 'Speyside, Spey',
    cask: 'First-fill barrel',
    price1: '220',
    price2: '40',
    color: '#71307C',
    isNew: true,
    isRightIcon: goods_icon_18,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 5,
  },
  {
    img: goods_5,
    no: 'CASK NO. 9.291',
    title: 'ROLL ON A HAPPY HAY BALE',
    type: 2,
    flavour: 'Sweet Fruity & Mellow',
    age: '20 years',
    region: 'Speyside Spey',
    cask: 'First-fill barrel',
    price1: '290',
    price2: '10',
    color: '#71307C',
    isNew: true,
    isRightIcon: goods_icon_5,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 6,
  },

  {
    img: goods_19,
    no: 'CASK NO. 78.74',
    title: 'Cheeky wee upstart',
    type: 2,
    flavour: 'Young & Spritely',
    age: '9 years',
    region: 'Highland Western',
    cask: 'Second-fill Pedro Ximenez hogshead',
    price1: '130',
    price2: '94',
    color: '#d298c4',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 7,
  },
  {
    img: goods_13,
    no: 'CASK NO. 95.79',
    title: "Cross-cultural",
    type: 2,
    flavour: 'Deep Rich & Dried Fruits',
    age: '14 years',
    region: 'Speyside Lossie',
    cask: 'First-fill American oak Pedro Ximenez hogshead',
    price1: '160',
    price2: '19',
    color: '#E6782A',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 8,
  },
  {
    img: goods_12,
    no: 'CASK NO. 112.116',
    title: "Orchards in a blossom",
    type: 2,
    flavour: 'Juicy Oak & Vanilla',
    age: '8 years',
    region: 'Highland Southern',
    cask: 'First-fill barrel',
    price1: '110',
    price2: '49',
    color: '#60A8D3',
    isNew: true,
    hovered: false,
    hovered1: false,
    page: 'whisky',
    productNum: 1,
    id: 9,
  },
];


// State
export const STATETYPE = [
  {
    label: 'Alabama',
    value: 'Alabama',
  },
  {
    label: 'Alaska',
    value: 'Alaska',
  },
  {
    label: 'Arizona',
    value: 'Arizona',
  },
  {
    label: 'Arkansas',
    value: 'Arkansas',
  },
  {
    label: 'California',
    value: 'California',
  },
  {
    label: 'Colorado',
    value: 'Colorado',
  },
  {
    label: 'Connecticut',
    value: 'Connecticut',
  },
  {
    label: 'Delaware',
    value: 'Delaware',
  },
  {
    label: 'District of Columbia',
    value: 'District of Columbia',
  },
  {
    label: 'Florida',
    value: 'Florida',
  },
  {
    label: 'Georgia',
    value: 'Georgia',
  },
  {
    label: 'Hawaii',
    value: 'Hawaii',
  },
  {
    label: 'ldaho',
    value: 'ldaho',
  },
  {
    label: 'Illinois',
    value: 'Illinois',
  },
  {
    label: 'Indiana',
    value: 'Indiana',
  },
  {
    label: 'lowa',
    value: 'lowa',
  },
  {
    label: 'Kansas',
    value: 'Kansas',
  },
  {
    label: 'Kentucky',
    value: 'Kentucky',
  },
  {
    label: 'Louisiana',
    value: 'Louisiana',
  },
  {
    label: 'Maine',
    value: 'Maine',
  },
  {
    label: 'Maryland',
    value: 'Maryland',
  },
  {
    label: 'Massachusetts',
    value: 'Massachusetts',
  },
  {
    label: 'Michigan',
    value: 'Michigan',
  },
  {
    label: 'Minnesota',
    value: 'Minnesota',
  },
  {
    label: 'Mississippi',
    value: 'Mississippi',
  },
  {
    label: 'Missouri',
    value: 'Missouri',
  },
  {
    label: 'Montana',
    value: 'Montana',
  },
  {
    label: 'Nebraska',
    value: 'Nebraska',
  },
  {
    label: 'Nevada',
    value: 'Nevada',
  },
  {
    label: 'New Hampshire',
    value: 'New Hampshire',
  },
  {
    label: 'New Jersey',
    value: 'New Jersey',
  },
  {
    label: 'New Mexico',
    value: 'New Mexico',
  },
  {
    label: 'New York',
    value: 'New York',
  },
  {
    label: 'North Carolina',
    value: 'North Carolina',
  },
  {
    label: 'North Dakota',
    value: 'North Dakota',
  },
  {
    label: 'Ohio',
    value: 'Ohio',
  },
  {
    label: 'Oklahoma',
    value: 'Oklahoma',
  },
  {
    label: 'Oregon',
    value: 'Oregon',
  },
  {
    label: 'Pennsylvania',
    value: 'Pennsylvania',
  },
  {
    label: 'Rhode Island',
    value: 'Rhode Island',
  },
  {
    label: 'South Carolina',
    value: 'South Carolina',
  },
  {
    label: 'South Dakota',
    value: 'South Dakota',
  },
  {
    label: 'Tennessee',
    value: 'Tennessee',
  },
  {
    label: 'Texas',
    value: 'Texas',
  },
  {
    label: 'Utah',
    value: 'Utah',
  },
  {
    label: 'Vermont',
    value: 'Vermont',
  },
  {
    label: 'Virginia',
    value: 'Virginia',
  },
  {
    label: 'Washington',
    value: 'Washington',
  },
  {
    label: 'West Virginia',
    value: 'West Virginia',
  },
  {
    label: 'Wisconsin',
    value: 'Wisconsin',
  },
  {
    label: 'Wyoming',
    value: 'Wyoming',
  },
];

// aboutType
export const ABOUTTYPE = [
  {
    label: 'Referred by member',
    value: 'Referred by member',
  },
  {
    label: 'An event - please specify',
    value: 'An event - please specify',
  },
  {
    label: 'Facebook',
    value: 'Facebook',
  },
  {
    label: 'Instagram',
    value: 'Instagram',
  },
  {
    label: 'YouTube (SMWS America channel)',
    value: 'YouTube (SMWS America channel)',
  },
  {
    label: 'Other - please specify',
    value: 'Other - please specify',
  }
];

// Delivery date
export const DELIVERY_DATE = [
  {
    label: 'Not specified',
    value: '0',
  },
  {
    label: '2024/04/30',
    value: '',
  },
  {
    label: '2024/05/01',
    value: '2024/05/01',
  },
  {
    label: '2024/05/02',
    value: '2024/05/02',
  },
  {
    label: '2024/05/03',
    value: '2024/05/03',
  },
  {
    label: '2024/05/04',
    value: '2024/05/04',
  },
  {
    label: '2024/05/05',
    value: '2024/05/05',
  },
  {
    label: '2024/05/06',
    value: '2024/05/06',
  },
  {
    label: '2024/05/07',
    value: '2024/05/07',
  },
  {
    label: '2024/05/08',
    value: '2024/05/08',
  },
  {
    label: '2024/05/09',
    value: '2024/05/09',
  },
  {
    label: '2024/05/10',
    value: '2024/05/10',
  },
  {
    label: '2024/05/11',
    value: '2024/05/11',
  }, {
    label: '2024/05/12',
    value: '2024/05/12',
  },
  {
    label: '2024/05/13',
    value: '2024/05/13',
  },
  {
    label: '2024/05/14',
    value: '2024/05/14',
  }
];

// Delivery Time
export const DELIVERY_TIME = [
  {
    label: 'Not specified',
    value: '0',
  },
  {
    label: 'AM(8:00-12:00)',
    value: '1',
  },
  {
    label: '14:00 ~ 16:00',
    value: '2',
  },
  {
    label: '16:00 ~ 18:00',
    value: '3',
  },
  {
    label: '18:00 ~ 20:00',
    value: '4',
  },
  {
    label: '19:00 ~ 21:00',
    value: '5',
  }
];